### ISSUE TITLE
Consider using a different variable name than "copyright"

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/pycoalaip#45]
See https://docs.python.org/3.5/library/constants.html#copyright

> The site module (which is imported automatically during startup, except if the -S command-line option is given) adds several constants to the built-in namespace. They are useful for the interactive interpreter shell and should not be used in programs.

Perhaps `copyright_` can be used instead. See http://legacy.python.org/dev/peps/pep-0008/#descriptive-naming-styles

**Comment by sohkai** [comment]
`copyright_` sounds like a good idea.
